# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db17ccba286a3b6dbc8deb56ec4f839a8bc91d0b583f8412bbe9f29f7e19a3d687e60ca15d40e4eca6bdc33ea4b2ef0f674b087bf684eb8ed5e1554a23181515

test:
  secret_key_base: e3f30e3b7482b0b11c40f83b38f6a40a1e0ce916d9777030b956678e0275d6cb134f1e182f32bf27d4f8dd0aa80742a9016443e279eae6d385fc01de0940b84e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
